# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 15:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genotype', models.CharField(max_length=50)),
                ('case_number', models.IntegerField(blank=True, null=True)),
                ('control_number', models.IntegerField(blank=True, null=True)),
                ('total_number', models.IntegerField(blank=True, null=True)),
                ('or_u', models.FloatField(blank=True, null=True)),
                ('hr_u', models.FloatField(blank=True, null=True)),
                ('rr_u', models.FloatField(blank=True, null=True)),
                ('ci_u_95', django.contrib.postgres.fields.ranges.FloatRangeField(blank=True, null=True)),
                ('p_u', models.CharField(blank=True, max_length=50, null=True)),
                ('or_m', models.FloatField(blank=True, null=True)),
                ('hr_m', models.FloatField(blank=True, null=True)),
                ('rr_m', models.FloatField(blank=True, null=True)),
                ('ci_m_95', django.contrib.postgres.fields.ranges.FloatRangeField(blank=True, null=True)),
                ('p_m', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceBasedMedicineLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebml', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_official_symbol', models.CharField(max_length=50, unique=True)),
                ('entrez_gene_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('gene_alternative_symbols', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('gene_official_full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gene_type', models.CharField(blank=True, max_length=50, null=True)),
                ('gene_summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prognosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prognosis_name', models.CharField(max_length=200)),
                ('prognosis_type', models.CharField(blank=True, max_length=50, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=200, null=True)),
                ('original', models.CharField(max_length=20)),
                ('case_meaning', models.CharField(blank=True, max_length=200, null=True)),
                ('control_meaning', models.CharField(blank=True, max_length=200, null=True)),
                ('total_meaning', models.CharField(blank=True, max_length=200, null=True)),
                ('annotation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('language', models.CharField(max_length=50)),
                ('pub_year', models.IntegerField()),
                ('pubmed_id', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(max_length=500)),
                ('pub_type', models.CharField(max_length=50)),
                ('ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_number', models.IntegerField(blank=True, null=True)),
                ('male', models.IntegerField(blank=True, null=True)),
                ('female', models.IntegerField(blank=True, null=True)),
                ('median_age', models.FloatField(blank=True, null=True)),
                ('mean_age', models.FloatField(blank=True, null=True)),
                ('age_range', django.contrib.postgres.fields.ranges.FloatRangeField(blank=True, null=True)),
                ('treatment_desc', models.TextField(blank=True, null=True)),
                ('treatment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ebml', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KB_SNP.EvidenceBasedMedicineLevel')),
            ],
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup', models.CharField(max_length=200)),
                ('prognosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KB_SNP.Prognosis')),
            ],
        ),
        migrations.CreateModel(
            name='Tumor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('mesh_term', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('mesh_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbsnp', models.CharField(max_length=200)),
                ('hgvs_g', models.CharField(blank=True, max_length=50, null=True)),
                ('hgvs_p', models.CharField(blank=True, max_length=50, null=True)),
                ('gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KB_SNP.Gene')),
            ],
        ),
        migrations.AddField(
            model_name='association',
            name='prognosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KB_SNP.Prognosis'),
        ),
        migrations.AddField(
            model_name='association',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KB_SNP.Research'),
        ),
        migrations.AddField(
            model_name='association',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KB_SNP.Subgroup'),
        ),
        migrations.AddField(
            model_name='association',
            name='tumor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KB_SNP.Tumor'),
        ),
        migrations.AddField(
            model_name='association',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KB_SNP.Variant'),
        ),
    ]
