# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KB_SNP', '0002_tumor_tumor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='journal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='afr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='allele',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='amr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='eas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='eur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='sas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
