# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-17 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KB_SNP', '0003_auto_20180427_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tumor',
            old_name='name',
            new_name='tumor_name',
        ),
        migrations.AddField(
            model_name='research',
            name='tumor_stage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
