# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 09:40
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Under Review', 'Under Review'), ('Revision', 'Revision'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=20)),
                ('kb', models.CharField(choices=[('SNP', 'SNP'), ('Expression', 'Expression')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('pubmed_id', models.IntegerField(blank=True, null=True)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('paper', models.FileField(blank=True, max_length=300, null=True, upload_to='uploads/%Y/%m%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
