# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KB_Exp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tumor',
            name='tumor_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='exp_detection_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tumor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
