# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KB_Exp', '0002_auto_20180313_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='journal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
